### PR TITLE
feat: Bubble UnUniFi NFT Plugin codes

### PR DESCRIPTION
**Pull request by Senna46**
Some codes for Bubble `UnUniFi NFT` Plugin

- [x]  MsgListNft
- [x]  MsgCancelNftListing
- [x] MsgEndNftListing
- [x] MsgExpandListingPeriod
```
Action expandListingPeriod - The plugin UnUniFi NFT (testing) / action expandListingPeriod threw the following error: Error: This type is not registered: undefined
    at Object.b [as instanceToProtoAny]
```
- [x]  MsgPlaceBid
```
run.js:8 Action placeBid - The plugin UnUniFi NFT (testing) / action placeBid threw the following error: TypeError: Cannot read properties of undefined (reading 'length')
```
- [x]  MsgCancelBid
- [x]  MsgPayFullBid
- [x]  MsgRepay
```
Action Repay - The plugin UnUniFi NFT (testing) / action Repay threw the following error: TypeError: Cannot read properties of undefined (reading 'length')
    at a (https://cdn.jsdelivr.net/npm/@cosmos-client/core@0.46.0-rc7/index.min.js:2:51140)
```
- [x] MsgBorrow
```
Action borrow - The plugin UnUniFi NFT (testing) / action borrow threw the following error: TypeError: Cannot read properties of undefined (reading 'length')
    at a (https://cdn.jsdelivr.net/npm/@cosmos-client/core@0.46.0-rc7/index.min.js:2:51140)
```
- [x] MsgLiquidate
- [x] MsgMintStableCoin
- [x] MsgBurnStableCoin

### CODE REVIEW

**Comment by Senna46** [comment]
i implemented Bubble Plugin & example-codes.
8/12 work, but 4/12 does not work now.

Bacause of ununifi-ts's problem, i think.

**Comment by Senna46** [comment]
i will try debug ununifi-ts cdn.

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 cc: @mkXultra 
I recommend that you first read the docs about the nftmarket module in the UnUniFi/chain repository to understand necessary parameters and then retry it. (It might be faster to ask @mkXultra  a question. But I leave it to you how to proceed.)

Second, there may be the following possibilities

- The implementation of the node that is running is outdated.
- The proto or swagger definition files from which ununifi-ts were generated is outdated.

It would be better to ask @mkXultra  about the actual situation in these status.
In some cases, I guess you should ask him to build a new node on the VPS, or ask him to show you how to build a new node on the VPS.

I guess you mainly need information related to genesis.json, and it would be better to have you look at the scripts in the CauchyE/utils repository or on the current alpha-test node, and then, ask @mkXultra about any questions you have, and then run the node with the new code and then retry to debug.

**Comment by Senna46** [comment]
work MsgRepay & MsgBorrow

but, does not work MsgExpandListingPeriod & MsgPlaceBid
```
Error: This type is not registered: undefined
    at Object.b [as instanceToProtoAny] (https://cdn.jsdelivr.net/npm/@cosmos-client/core@0.46.0-rc7/index.min.js:2:612565)
    at eval (PLUGIN_1655728213223x343825062515965950_current/UnUniFi-NFT--testing--action--expandListingPeriod-.js:146:35) (please check your plugin's code)
```
This problem maybe relate with https://github.com/cosmos-client/ununifi-ts/pull/7

**Comment by Senna46** [comment]
Somehow it has been a while since I ran it today and there were no errors. Strange...
スクリーンショット 2022-07-15 153927

**Review by uuyu-g — APPROVED** [review]
LGTM

**Pull request merged**
